# Generated by Django 3.0 on 2022-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220316_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '0'), ('moderator', '1'), ('admin', '2')], default='user', max_length=10, verbose_name='role'),
        ),
    ]
