# Generated by Django 3.0 on 2022-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220322_1852'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unnique_title_author',
        ),
    ]
